source/blog/urls.py
from django.urls import path
from .views import posts

urlpatterns = [
    # News view
    path("", posts.PostListView.as_view(), name="post_list"),
    path("<int:pk>/", posts.PostDetailView.as_view(), name="post_detail"),
]

source/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from api.v1 import urls as api_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path(f"api/v1/", include((api_urls, "api-v1"), namespace="api-v1")),
    path('api/schema/', SpectacularAPIView.as_view(api_version='api-v1'), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='docs'),
    path('account/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/models/course.py
from django.db import models

from PIL import Image
import os

from accounts.models import Teacher


class Course(models.Model):
    LANGUAGE_CHOICES = [
        ('EN', 'English'),
        ('RU', 'Russian'),
    ]

    SKILL_LEVEL_CHOICES = [
        ('ALL', 'All Levels'),
        ('BEGINNER', 'Beginner'),
        ('INTERMEDIATE', 'Intermediate'),
        ('ADVANCED', 'Advanced'),
    ]

    teacher = models.ForeignKey(
        Teacher,
        on_delete=models.PROTECT,
        verbose_name='Преподаватель',
        related_name='teacher',
    )
    title = models.CharField(
        max_length=255,
        null=False,
        blank=False,
        verbose_name="Название"
    )
    preview_description = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name='Preview Description For Course List Page'
    )
    description = models.TextField(
        max_length=3000,
        null=False,
        blank=False,
        verbose_name='Description'
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=False,
        blank=False,
        verbose_name="Цена"
    )
    image = models.ImageField(
        upload_to='course_images/',
        null=True,
        blank=True,
        verbose_name="Image"
    )
    language = models.CharField(
        max_length=2,
        choices=LANGUAGE_CHOICES,
        default='EN',
        verbose_name="Язык"
    )
    skill_level = models.CharField(
        max_length=12,
        choices=SKILL_LEVEL_CHOICES,
        default='ALL',
        verbose_name="Skill Level"
    )
    tag = models.ManyToManyField(
        to='webapp.Tag',
        related_name='tags',
        blank=True
    )
    is_active = models.BooleanField(
        verbose_name='Активен',
        null=False,
        default=True
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Created at"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Updated at",
        null=True
    )

    def save(self, *args, **kwargs):
        try:
            this = Course.objects.get(id=self.id)
            if this.image and self.image != self.image:
                if os.path.isfile(this.image.path):
                    this.image.delete(save=False)
        except Course.DoesNotExist:
            pass

        super().save(*args, **kwargs)

        if self.image:
            self.crop_image()

    def crop_image(self):
        if os.path.isfile(self.image.path):  # Add this check
            img = Image.open(self.image.path)
            width, height = img.size
            aspect_ratio = 16 / 9

            if width / height > aspect_ratio:
                new_width = int(height * aspect_ratio)
                new_height = height
                left = (width - new_width) / 2
                top = 0
                right = (width + new_width) / 2
                bottom = new_height
            else:
                new_width = width
                new_height = int(width / aspect_ratio)
                left = 0
                top = (height - new_height) / 2
                right = new_width
                bottom = (height + new_height) / 2

            img = img.crop((left, top, right, bottom))
            img.save(self.image.path)

    def __str__(self):
        return f'{self.id} {self.title}'

    class Meta:
        verbose_name = 'Course'
        verbose_name_plural = 'Courses'

source/templates/error.html
{% extends 'base.html' %}

source/templates/new_base.html
{% load i18n %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="zxx">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- IcoFont Min CSS -->
    <link rel="stylesheet" href="{% static 'css/icofont.min.css' %}">
    <!-- Classy Nav CSS -->
    <link rel="stylesheet" href="{% static 'css/classy-nav.min.css' %}">
    <!-- Animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <!-- Owl Carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- Magnific Popup CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.min.css' %}">
    <!-- Owl Theme Default CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    {% block links %}{% endblock %}

    {% block header %} {% endblock %}

    <title>{% block title %}PDGA{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static '/img/favicon.png' %}">
</head>
<body>
<!-- Start Preloader Area -->
<div class="preloader-area">
    <div class="loader">
        <div class="dots">
            <i class="dots-item dots-item-move-down"></i>
            <i class="dots-item dots-item-move-left"></i>
            <i class="dots-item dots-item-move-left"></i>
            <i class="dots-item dots-item-move-left"></i>
            <i class="dots-item dots-item-move-left"></i>
            <i class="dots-item dots-item-move-down"></i>
            <i class="dots-item dots-item-move-right"></i>
            <i class="dots-item dots-item-move-right"></i>
            <i class="dots-item dots-item-move-down"></i>
            <i class="dots-item dots-item-move-up"></i>
            <i class="dots-item dots-item-move-down"></i>
            <i class="dots-item dots-item-move-up"></i>

            <i class="dots-item"></i>

            <i class="dots-item dots-item-move-down"></i>
            <i class="dots-item dots-item-move-up"></i>
            <i class="dots-item dots-item-move-down"></i>
            <i class="dots-item dots-item-move-up"></i>
            <i class="dots-item dots-item-move-left"></i>
            <i class="dots-item dots-item-move-left"></i>
            <i class="dots-item dots-item-move-up"></i>
            <i class="dots-item dots-item-move-right"></i>
            <i class="dots-item dots-item-move-right"></i>
            <i class="dots-item dots-item-move-right"></i>
            <i class="dots-item dots-item-move-right"></i>
            <i class="dots-item dots-item-move-up"></i>
        </div>
    </div>
</div>
<!-- End Preloader Area -->

<!-- Start Main Menu Area -->
<div class="main-header-area {% block navbar-area %}navbar-area{% endblock %} header-sticky">
    <div class="container">
        <div class="classy-nav-container breakpoint-off">
            <!-- Classy Menu -->
            <nav class="classy-navbar justify-content-between" id="EduStudyNav">

                <!-- Logo -->
                <a class="nav-brand" href="{% url 'index' %}"><img src="{% static '/img/logo.png' %}" alt="logo"></a>

                <!-- Navbar Toggler -->
                <div class="classy-navbar-toggler">
                    <span class="navbarToggler"><span></span><span></span><span></span></span>
                </div>

                <!-- Menu -->
                <div class="classy-menu">

                    <!-- close btn -->
                    <div class="classycloseIcon">
                        <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                    </div>

                    <!-- Nav Start -->
                    <div class="classynav">
                        <ul>
                            <li class="mr-ul"><a href="{% url 'course_list' %}">{% trans 'Courses' %}</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'course_list' %}">{% trans 'All Courses' %}</a></li>
                                    {% if request.user.is_authenticated %}
                                        <li><a href="{% url 'course_paid_list' %}">{% trans 'Paid Courses' %}</a></li>
                                    {% endif %}
                                </ul>
                            </li>

                            <li class="mr-ul">
                                <a href="{% url 'teacher_list' %}">{% trans 'Teachers' %}</a>
                            </li>
                        
                            <li class="mr-ul">
                                <a href="{% url 'post_list' %}">{% trans 'Blog' %}</a>
                            </li>

                            <li class="mr-ul">
                                <a href="{% url 'contact_us' %}">{% trans 'Contact Us' %}</a>
                            </li>


                            {% if request.user.is_authenticated %}
                                <li class="">
                                    <a href="{% url 'user_detail' request.user.pk %}"> {% trans "Account" %}</a>
                                </li>
                            {% else %}
                                <li class="">
                                    <a href="{% url 'login' %}"> {% trans "Log in" %}</a>
                                </li>
                            {% endif %}

                            <li>
                                <a>
                                    {% if request.LANGUAGE_CODE == 'en' %}
                                        EN
                                    {% else %}
                                        RU
                                    {% endif %}
                                </a>
                                <ul class="dropdown">
                                    <form action="{% url 'set_language' %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="next" value="{{ request.path }}">
                                        <!-- Вернуться на текущую страницу -->
                                        <li>
                                            <button class="change-language-buttons" type="submit" name="language"
                                                    value="en">EN
                                            </button>
                                        </li>
                                        <li>
                                            <button class="change-language-buttons" type="submit" name="language"
                                                    value="ru">RU
                                            </button>
                                        </li>
                                    </form>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <!-- Nav End -->
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- End Main Menu Area -->

{% block content %}
{% endblock %}

<!-- Start Footer Area -->
<footer class="footer-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="single-footer">
                    <h3>{% trans 'About PDGA' %}</h3>

                    <ul class="footer-contact-info">
                        <li>{% trans 'Kazakhstan, Almaty' %}, {% trans 'Zheltoksan 37 "Trade Union"' %} </li>
                        <li><a href="tel:+77052889271">+7 (705) 288-92-71</a></li>
                        <li><a href="tel:+77273802349">+7 (727) 380-23-49</a></li>
                        <li><a href="mailto:info@boston-school.kz">info@boston-school.kz</a></li>
                    </ul>

                    <ul class="social">
                        <li><a href="#"><i class="icofont-facebook"></i></a></li>
                        <li><a href="#"><i class="icofont-twitter"></i></a></li>
                        <li><a href="#"><i class="icofont-linkedin"></i></a></li>
                        <li><a href="#"><i class="icofont-google-plus"></i></a></li>
                        <li><a href="#"><i class="icofont-pinterest"></i></a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="single-footer">
                    <h3>{% trans 'Courses' %}</h3>

                    <ul class="list">
                        <li><a href="{% url 'course_list' %}">{% trans 'All Courses' %}</a></li>
                        <li><a href="{% url 'teacher_list' %}">{% trans 'Teachers' %}</a></li>
                        <li><a href="#">Blog</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="single-footer">
                    <h3>{% trans 'More' %}</h3>

                    <ul class="list">
                        <li><a href="blog-style-one.html">Blog</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="single-footer">
                    <h3>{% trans 'Support' %}</h3>

                    <ul class="list">
                        <li><a href="{% url 'contact_us' %}">{% trans 'Contact Us' %}</a></li>
                        {% if request.user.is_authenticated %}
                            <li class="">
                                <a href="{% url 'user_detail' request.user.pk %}"> {% trans "Account" %}</a>
                            </li>
                        {% else %}
                            <li class="">
                                <a href="{% url 'login' %}"> {% trans "Log in" %}</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="copyright-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-7">
                    <p>© <span>PDGA</span>. {% trans 'All rights reserved' %}.</p>
                </div>

{#                <div class="col-lg-5 col-md-5">#}
{#                    <ul>#}
{#                        <li><a href="#">Privacy Policy</a></li>#}
{#                        <li><a href="#">Terms & Conditions</a></li>#}
{#                    </ul>#}
{#                </div>#}
            </div>
        </div>
    </div>
</footer>
<!-- End Footer Area -->

<!-- Back to top -->
<a class="scrolltop" href="#top"><i class="icofont-hand-drawn-up"></i></a>
<!-- End Back to top -->

<!-- jQuery Min JS -->
<script src="{% static '/js/jquery.min.js' %}"></script>
<!-- Bootstrap Min JS -->
<script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
<!-- Classy Nav Min Js -->
<script src="{% static '/js/classy-nav.min.js' %}"></script>
<!-- Owl Carousel Min Js -->
<script src="{% static '/js/owl.carousel.min.js' %}"></script>
<!-- Magnific Popup JS -->
<script src="{% static '/js/jquery.magnific-popup.min.js' %}"></script>
<!-- CounterUp JS -->
<script src="{% static '/js/jquery.counterup.min.js' %}"></script>
<!-- Waypoints JS -->
<script src="{% static '/js/waypoints.min.js' %}"></script>
<!-- Form Validator Min JS -->
<script src="{% static '/js/form-validator.min.js' %}"></script>
<!-- Contact Form Min JS -->
<script src="{% static '/js/contact-form-script.js' %}"></script>
<!-- Main JS -->
<script src="{% static '/js/main.js' %}"></script>
</body>
</html>